name: Build Master - Publish npm
on:
  release:
    types:
      - published
jobs:
  build:
    name: Build npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # npm install from package-lock.json(npm ci(Continuous Integration))
      - name: npm_ci
        run: npm ci
        id: npm_ci

      # npm publish
      - name: npm_publish
        run: npm publish
        id: npm_publish